### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by DamonGant** [glynnbird/yub#13]
These might be useful to TypeScript users. They could be uploaded to DefinitelyTyped or included in the repo.

    declare module "yub" {
      interface YubResponse {
        t?: string | Date,
        otp: string,
        nonce?: any,
        sl?: string,
        status?: any,
        signatureVerified: boolean,
        nonceVerified: boolean,
        identity?: string,
        encrypted: string,
        encryptedHex: string,
        serial?: number,
        valid: boolean
      }

      interface YubCallback {
        (err: Error, response: YubResponse)
      }

      export function init(client_id: string, secret_key: string) : void;
      export function verify(otp: string, callback: YubCallback) : void;
      export function verifyOffline(otp: string, callback: YubCallback) : void;
    }

**Comment by glynnbird** [comment]
Fixed in 0.10.13
