### ISSUE TITLE
yub.verifyOffline

### ISSUE THREAD

**Issue by gregbenner** [glynnbird/yub#8]
the main verify is working well, but I was playing around to see if the offline check works and it doesn't seem to

      `// try online verify if there's an error fallback and try offline verify`

    function verify(OTP) {

	yub.verify(OTP, function(err,data) {

	  console.log(err, data);

	  if (err) {

	  	yub.verifyOffline(OTP, function(err,data) {

	  		console.log(err, data);

	  	});

	  }

	});
    }

**Comment by glynnbird** [comment]
I've just tried the offline version on my machine like this:

```
var otp = "123456"; 
yub.verifyOffline(otp, function(err,data) {
  if(err) {
    console.log("Error");
  }
  if (data.identity && data.serial) {
    console.log(data);
  } else {
    console.log("Invalid OTP");
  }
});
```

and it seems to work fine.

**Comment by gregbenner** [comment]
I tried with an otp from the yubikey does that make a difference? I'll try your example also to double check tomorrow.

**Comment by glynnbird** [comment]
Yes I should have been clearer. In the above example, the `otp` variable would contain your own OTP string from your own yubikey.

**Comment by gregbenner** [comment]
Tried with the code provided and the offline still seems to fail for me. I don't need the functionality, was just playing around but just thought I'd let you know.

My output with the verifyOffline and a real OTP from yubikey
<img width="397" alt="screen shot 2016-03-06 at 12 30 02" src="https://cloud.githubusercontent.com/assets/1177690/13555784/68a98b1e-e397-11e5-8c27-c70dd7230b8f.png">

My output with the normal verify and a real OTP from yubikey
<img width="408" alt="screen shot 2016-03-06 at 12 30 37" src="https://cloud.githubusercontent.com/assets/1177690/13555785/68b790b0-e397-11e5-8fe6-6b94a0ccbc95.png">

**Comment by glynnbird** [comment]
The output from "verifyOffline" is different from "verify" because it is really only checking that your OTP is the right length. When doing online verification, it calls the Yubikey API to check that the OTP is valid but when working offline, it can't do this so can only really do string manipulation on the OTP.

**Comment by gregbenner** [comment]
Ah yeah maybe worth mentioning on README it doesn't do any kind of verification then, just checking string length. Also there is nothing returning true or verified in my example "valid: false".

**Comment by glynnbird** [comment]
I think it's fair to say that the readme does mention this: https://github.com/glynnbird/yub#offline-verification
